<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Coach extends \App\Entity\Coach implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Coach' . "\0" . 'idCoach', '' . "\0" . 'App\\Entity\\Coach' . "\0" . 'nomCoach', '' . "\0" . 'App\\Entity\\Coach' . "\0" . 'prenomCoach', '' . "\0" . 'App\\Entity\\Coach' . "\0" . 'dateNaissance', '' . "\0" . 'App\\Entity\\Coach' . "\0" . 'grade', '' . "\0" . 'App\\Entity\\Coach' . "\0" . 'dateFinContrat', '' . "\0" . 'App\\Entity\\Coach' . "\0" . 'adresseMail', '' . "\0" . 'App\\Entity\\Coach' . "\0" . 'salaire', '' . "\0" . 'App\\Entity\\Coach' . "\0" . 'nbTropheLocaux', '' . "\0" . 'App\\Entity\\Coach' . "\0" . 'nbTropheInternationaux', '' . "\0" . 'App\\Entity\\Coach' . "\0" . 'formationPrefere', '' . "\0" . 'App\\Entity\\Coach' . "\0" . 'imageFormation', '' . "\0" . 'App\\Entity\\Coach' . "\0" . 'imageCoach', '' . "\0" . 'App\\Entity\\Coach' . "\0" . 'age', '' . "\0" . 'App\\Entity\\Coach' . "\0" . 'mdpCoach', 'captchaCode'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Coach' . "\0" . 'idCoach', '' . "\0" . 'App\\Entity\\Coach' . "\0" . 'nomCoach', '' . "\0" . 'App\\Entity\\Coach' . "\0" . 'prenomCoach', '' . "\0" . 'App\\Entity\\Coach' . "\0" . 'dateNaissance', '' . "\0" . 'App\\Entity\\Coach' . "\0" . 'grade', '' . "\0" . 'App\\Entity\\Coach' . "\0" . 'dateFinContrat', '' . "\0" . 'App\\Entity\\Coach' . "\0" . 'adresseMail', '' . "\0" . 'App\\Entity\\Coach' . "\0" . 'salaire', '' . "\0" . 'App\\Entity\\Coach' . "\0" . 'nbTropheLocaux', '' . "\0" . 'App\\Entity\\Coach' . "\0" . 'nbTropheInternationaux', '' . "\0" . 'App\\Entity\\Coach' . "\0" . 'formationPrefere', '' . "\0" . 'App\\Entity\\Coach' . "\0" . 'imageFormation', '' . "\0" . 'App\\Entity\\Coach' . "\0" . 'imageCoach', '' . "\0" . 'App\\Entity\\Coach' . "\0" . 'age', '' . "\0" . 'App\\Entity\\Coach' . "\0" . 'mdpCoach', 'captchaCode'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Coach $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCaptchaCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCaptchaCode', []);

        return parent::getCaptchaCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCaptchaCode($captchaCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCaptchaCode', [$captchaCode]);

        return parent::setCaptchaCode($captchaCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCoach(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdCoach();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCoach', []);

        return parent::getIdCoach();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomCoach(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomCoach', []);

        return parent::getNomCoach();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomCoach(string $nomCoach): \App\Entity\Coach
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomCoach', [$nomCoach]);

        return parent::setNomCoach($nomCoach);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenomCoach(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenomCoach', []);

        return parent::getPrenomCoach();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenomCoach(string $prenomCoach): \App\Entity\Coach
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenomCoach', [$prenomCoach]);

        return parent::setPrenomCoach($prenomCoach);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateNaissance(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateNaissance', []);

        return parent::getDateNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateNaissance(\DateTimeInterface $dateNaissance): \App\Entity\Coach
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateNaissance', [$dateNaissance]);

        return parent::setDateNaissance($dateNaissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrade(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrade', []);

        return parent::getGrade();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrade(?string $grade): \App\Entity\Coach
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrade', [$grade]);

        return parent::setGrade($grade);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateFinContrat(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateFinContrat', []);

        return parent::getDateFinContrat();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateFinContrat(\DateTimeInterface $dateFinContrat): \App\Entity\Coach
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateFinContrat', [$dateFinContrat]);

        return parent::setDateFinContrat($dateFinContrat);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresseMail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresseMail', []);

        return parent::getAdresseMail();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresseMail(string $adresseMail): \App\Entity\Coach
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresseMail', [$adresseMail]);

        return parent::setAdresseMail($adresseMail);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalaire(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalaire', []);

        return parent::getSalaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalaire(float $salaire): \App\Entity\Coach
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalaire', [$salaire]);

        return parent::setSalaire($salaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbTropheLocaux(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbTropheLocaux', []);

        return parent::getNbTropheLocaux();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbTropheLocaux(int $nbTropheLocaux): \App\Entity\Coach
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbTropheLocaux', [$nbTropheLocaux]);

        return parent::setNbTropheLocaux($nbTropheLocaux);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbTropheInternationaux(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbTropheInternationaux', []);

        return parent::getNbTropheInternationaux();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbTropheInternationaux(int $nbTropheInternationaux): \App\Entity\Coach
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbTropheInternationaux', [$nbTropheInternationaux]);

        return parent::setNbTropheInternationaux($nbTropheInternationaux);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormationPrefere(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormationPrefere', []);

        return parent::getFormationPrefere();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormationPrefere(string $formationPrefere): \App\Entity\Coach
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormationPrefere', [$formationPrefere]);

        return parent::setFormationPrefere($formationPrefere);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageFormation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageFormation', []);

        return parent::getImageFormation();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageFormation($imageFormation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageFormation', [$imageFormation]);

        return parent::setImageFormation($imageFormation);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageCoach()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageCoach', []);

        return parent::getImageCoach();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageCoach($imageCoach)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageCoach', [$imageCoach]);

        return parent::setImageCoach($imageCoach);
    }

    /**
     * {@inheritDoc}
     */
    public function getAge(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAge', []);

        return parent::getAge();
    }

    /**
     * {@inheritDoc}
     */
    public function setAge(int $age): \App\Entity\Coach
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAge', [$age]);

        return parent::setAge($age);
    }

    /**
     * {@inheritDoc}
     */
    public function getMdpCoach(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMdpCoach', []);

        return parent::getMdpCoach();
    }

    /**
     * {@inheritDoc}
     */
    public function setMdpCoach(?string $mdpCoach): \App\Entity\Coach
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMdpCoach', [$mdpCoach]);

        return parent::setMdpCoach($mdpCoach);
    }

}
