<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container16HinFR\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container16HinFR/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container16HinFR.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container16HinFR\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container16HinFR\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '16HinFR',
    'container.build_id' => 'd196d58e',
    'container.build_time' => 1619744297,
], __DIR__.\DIRECTORY_SEPARATOR.'Container16HinFR');
